services:
  - type: web
    name: clara-lite-backend
    env: python
    plan: free
    rootDir: .
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GROQ_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false

      - key: LANGFUSE_PUBLIC_KEY
        sync: false
      - key: LANGFUSE_SECRET_KEY
        sync: false
      - key: LANGFUSE_HOST
        value: https://hipaa.cloud.langfuse.com
      - key: HF_TOKEN
        sync: false


  - type: web
    name: clara-lite-frontend
    env: node
    plan: free
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    startCommand: "npm run start"
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: clara-lite-backend
          envVarKey: RENDER_EXTERNAL_URL
